"""initial schema

Revision ID: d4b8c779fae3
Revises: 
Create Date: 2026-07-14 23:55:54.518317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b8c779fae3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('restaurant', 'cafe', 'park', 'mall', 'library', 'gym', 'hospital', 'tourist_attraction', name='place_category'), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('approx_rating', sa.Float(), nullable=True),
    sa.Column('price_range', sa.String(length=20), nullable=True),
    sa.Column('avg_price_inr', sa.Float(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=True),
    sa.Column('popular_time_slot', sa.String(length=50), nullable=True),
    sa.Column('eco_friendly', sa.Boolean(), nullable=False),
    sa.Column('sustainability_score', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('coordinates_estimated', sa.Boolean(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('photo_reference', sa.String(length=500), nullable=True),
    sa.Column('photo_attribution', sa.String(length=500), nullable=True),
    sa.CheckConstraint('sustainability_score IS NULL OR sustainability_score BETWEEN 1 AND 5', name='ck_places_sustainability_score_range'),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('budget_default', sa.Float(), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lon', sa.Float(), nullable=True),
    sa.Column('college_lat', sa.Float(), nullable=True),
    sa.Column('college_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('interactions',
    sa.Column('interaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('click', 'bookmark', 'dismiss', 'order_intent', name='interaction_action'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_index(op.f('ix_interactions_place_id'), 'interactions', ['place_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('restaurant', 'cafe', 'park', 'mall', 'library', 'gym', 'hospital', 'tourist_attraction', name='place_category'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_place_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('places')
    # ### end Alembic commands ###
